### ISSUE TITLE
Implement basic search & filtering UI

### ISSUE THREAD

**Issue by ryanoconnor7** [ryanoconnor7/FindADoctor#1]
Add the existing filter options for the API call to the UI and link it with `InputManager.js` where we will prepare it for the Yext API call.

- Main Search (text) `main-search`
- Zip (text) `zip-code-search`
- Insurance (drop down) `insurance-search
- Gender (drop down) `gender-search`
- Language (drop down) `language-search`
- Pediatric/Adult (drop down) `age-search`

**Comment by dzahnn** [comment]
done
